package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, November 20, 2024 3:34:06 PM IST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
